DROP TABLE IF EXISTS city;

CREATE TABLE city (
  id INT AUTO_INCREMENT PRIMARY KEY,
  city_name VARCHAR(500) DEFAULT NULL,
  aqi INT DEFAULT NULL,
  no2 INT DEFAULT NULL,
  o3 INT DEFAULT NULL,
  pm10 INT DEFAULT NULL
);